services:
  mysql:
    container_name: instaclone_mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instaclone
      MYSQL_USER: instaclone
      MYSQL_PASSWORD: instaclone
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    image: instaclone/backend
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    ports:
      - "8000:8000"
    volumes:
      - app_storage:/app/storage
    depends_on:
      - mysql

volumes:
  mysql_data: {}
  app_storage: {}
